# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    base_path: "build/ckeditor"
    js_path: "build/ckeditor/ckeditor.js"
#    jquery: true
    auto_inline: false

    plugins:
        codesnippet:
            path: "build/ckeditor/plugins/codesnippet/"
            filename: "plugin.js"

    configs:
        code_config:
            toolbar: "code"
            uiColor: "#403547"
    toolbars:
        configs:
            code:
                [['CodeSnippet']]

