# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    base_path: "build/ckeditor"
    js_path: "build/ckeditor/ckeditor.js"
    plugins:
        codesnippet:
            path: "build/ckeditor/plugins/codesnippet/"
            filename: "plugin.js"
    configs:
        code_config:
            toolbar: "code"
            uiColor: "#ffffff"
        note_config:
            toolbar: "note"
            uiColor: "#ffffff"
        letter_config:
            toolbar: "letter"
            uiColor: "#ffffff"
    toolbars:
        configs:
            code:
                [['CodeSnippet']]

            letter: [
                ['Bold', 'Italic', 'Strike', '-', 'RemoveFormat'], ["Source"],
                ["Align left", "Align right", "Center", "Justify" ],
                [
                        'JustifyLeft',
                        'JustifyCenter',
                        'JustifyRight',
                        'JustifyBlock',
                ],
                ['TextColor']
            ]
            note: [
            ]
